// CPU-only bounded file bridge to the SNAPSHOT of actual production math.
// Inputs/outputs are FP64 little-endian raw arrays generated by Python oracle.
#include "mamba3_layer_math.h"
#include <fstream>
#include <iostream>
#include <vector>
#include <string>
#include <stdexcept>
namespace mb=nsos::mamba3_block;
template<class T> std::vector<T> read(const std::string& path,std::size_t n) {
    std::vector<double> raw(n);std::ifstream f(path,std::ios::binary);
    if(!f.read(reinterpret_cast<char*>(raw.data()),n*sizeof(double))) throw std::runtime_error("read "+path);
    return std::vector<T>(raw.begin(),raw.end());
}
template<class T> void write(const std::string& path,const std::vector<T>& v) {
    std::vector<double> raw(v.begin(),v.end());std::ofstream f(path,std::ios::binary);
    if(!f.write(reinterpret_cast<const char*>(raw.data()),raw.size()*sizeof(double))) throw std::runtime_error("write "+path);
}
template<class T> struct OwnedState {
    std::vector<T> phase,ssm,k,v;
    OwnedState(const mb::Shape& s):phase(s.batch*s.heads*s.rotary_pairs),ssm(s.batch*s.heads*s.head_dim*s.state_dim),k(s.batch*s.heads*s.rank*s.state_dim),v(s.batch*s.heads*s.head_dim) {}
    mb::State<T> ptr() {return {phase.data(),ssm.data(),k.data(),v.data()};}
    mb::State<const T> src() const {return {phase.data(),ssm.data(),k.data(),v.data()};}
    void load(const std::string& dir) {phase=read<T>(dir+"phase.bin",phase.size());ssm=read<T>(dir+"ssm.bin",ssm.size());k=read<T>(dir+"k.bin",k.size());v=read<T>(dir+"v.bin",v.size());}
    void save(const std::string& dir) {write(dir+"phase.bin",phase);write(dir+"ssm.bin",ssm);write(dir+"k.bin",k);write(dir+"v.bin",v);}
};
template<class T> void run(const mb::Shape& s,const std::string& dir,const std::string& tag) {
    const mb::Layout l(s);const auto rows=std::size_t(s.batch)*s.sequence;
    auto p=read<T>(dir+"projection.bin",rows*s.width()),w=read<T>(dir+"core.bin",l.total),dy=read<T>(dir+"dy.bin",rows*s.inner());
    auto lengths=read<double>(dir+"valid.bin",s.batch);std::vector<int> valid(lengths.begin(),lengths.end());
    OwnedState<T> initial(s),final(s),seed(s),di(s);initial.load(dir+"initial_");seed.load(dir+"seed_");
    std::vector<T> history(mb::history_size(s)),q(mb::rotation_size(s)),k(q.size()),phase(mb::phase_size(s)),readout(mb::readout_size(s)),out(rows*s.inner()),status(s.batch),dx(rows*s.width()),dp(s.batch*l.total),scratch(s.batch*mb::scratch_per_head(s));
    mb::Trace<T> tr{history.data(),q.data(),k.data(),phase.data(),readout.data()};
    mb::Trace<const T> ctr{history.data(),q.data(),k.data(),phase.data(),readout.data()};
    for(int b=0;b<s.batch;++b) mb::detail::forward_batch(s,l,b,p.data(),w.data(),valid.data(),initial.src(),final.ptr(),tr,out.data(),status.data());
    for(int b=0;b<s.batch;++b) mb::detail::backward_batch(s,l,b,p.data(),w.data(),valid.data(),initial.src(),ctr,dy.data(),seed.src(),dx.data(),dp.data()+std::size_t(b)*l.total,di.ptr(),scratch.data()+std::size_t(b)*mb::scratch_per_head(s),status.data());
    std::vector<T> total(l.total);for(int b=0;b<s.batch;++b) for(std::size_t i=0;i<l.total;++i) total[i]+=dp[std::size_t(b)*l.total+i];
    write(dir+tag+"output.bin",out);write(dir+tag+"dx.bin",dx);write(dir+tag+"dp.bin",total);write(dir+tag+"status.bin",status);final.save(dir+tag+"final_");di.save(dir+tag+"dinitial_");
}
int main(int argc,char** argv) {try {
    if(argc!=3) throw std::runtime_error("probe_current_math <case-dir-with-slash> <shape-file>");
    mb::Shape s;std::ifstream f(argv[2]);int mimo,norm;
    f>>s.batch>>s.sequence>>s.model>>s.heads>>s.groups>>s.head_dim>>s.state_dim>>s.rank>>s.rotary_pairs>>mimo>>norm;s.mimo=mimo;s.out_norm=norm;
    if(!f||!mb::eligible(s)) throw std::runtime_error("ineligible fixture");
    run<double>(s,argv[1],"fp64_");run<float>(s,argv[1],"fp32_");
    std::cout<<"CURRENT SOURCE CPU FP64/FP32 PASS launch fixture\n";return 0;
}catch(const std::exception& e) {std::cerr<<e.what()<<'\n';return 1;}}
