#include "gpu_parity_common.h"
#include "mamba3_projection_controltail_oracle.h"
#include "cuda/mamba3_projection_wmma.cuh"
#include "mamba3_layer.h"
#include "mamba3_reference.h"
#include "gpu_execution.h"
#include "jamba.h"
#include "trainer.h"
#include <filesystem>
#include <algorithm>
#include <array>
#include <cstring>
#include <limits>

using namespace nsos;
namespace mp=nsos::mamba3_projection;
namespace ref=nsos::mamba3_reference;
namespace mb=nsos::mamba3_block;
namespace {
void require(bool ok,const char* why) {if(!ok) throw std::runtime_error(why);}
template<class F> void reject(F&& f,const char* why) {bool failed=false;try{f();}catch(const std::exception&){failed=true;}require(failed,why);}
void env(const char* value) {
#ifdef _WIN32
    _putenv_s("NSOS_MAMBA3_PROJECTION_PROVIDER",value?value:"");
#else
    if(value) setenv("NSOS_MAMBA3_PROJECTION_PROVIDER",value,1);
    else unsetenv("NSOS_MAMBA3_PROJECTION_PROVIDER");
#endif
}
const char* name(mp::Policy mode) {return mode==mp::Policy::BF16?"rdna_bf16_v1":"rdna_fp16_v1";}
double rounded(float x,mp::Policy mode) {
    if(!std::isfinite(x)||x==0) return x;
    if(mode==mp::Policy::BF16) {
        std::uint32_t bits;std::memcpy(&bits,&x,sizeof(bits));
        bits+=0x7fffu+((bits>>16)&1u);bits&=0xffff0000u;
        float y;std::memcpy(&y,&bits,sizeof(y));return y;
    }
    int e=0;const double magnitude=std::abs(double(x));std::frexp(magnitude,&e);
    const double quantum=std::ldexp(1.,std::max(-24,e-11));
    const double units=magnitude/quantum,base=std::floor(units),rest=units-base;
    const double integer=base+(rest>.5||(rest==.5&&std::fmod(base,2.)==1.)?1.:0.);
    const double value=integer*quantum;
    return std::copysign(value>65504.?std::numeric_limits<double>::infinity():value,x);
}
std::vector<double> values(const Tensor& t) {auto h=t.cpu();return {h.data(),h.data()+h.size};}
void fill(Tensor& t,float scale=.13f) {for(std::size_t i=0;i<t.size;++i)t.data()[i]=scale*std::sin(.173f*float(i+1));}
void close(const Tensor& actual,const std::vector<double>& expected,const char* why,double tol=4e-4) {
    auto got=values(actual);require(got.size()==expected.size(),"oracle extent");
    for(std::size_t i=0;i<got.size();++i) if(!std::isfinite(got[i])||std::abs(got[i]-expected[i])>tol*(1+std::abs(expected[i])))
        throw std::runtime_error(std::string(why)+" index="+std::to_string(i)+" got="+std::to_string(got[i])+" expected="+std::to_string(expected[i]));
}
std::vector<double> dense(mp::Policy mode,const std::vector<double>& a,const std::vector<double>& b,
    bool ta,bool tb,int M,int N,int K,mp::ExactAxis axis=mp::ExactAxis::None,int begin=0) {
    std::vector<double> out(std::size_t(M)*N);
    for(int m=0;m<M;++m) for(int n=0;n<N;++n) for(int k=0;k<K;++k) {
        const float av=float(a[ta?std::size_t(k)*M+m:std::size_t(m)*K+k]);
        const float bv=float(b[tb?std::size_t(n)*K+k:std::size_t(k)*N+n]);
        const bool exact=(axis==mp::ExactAxis::OutputRows&&m>=begin)||
            (axis==mp::ExactAxis::OutputCols&&n>=begin)||(axis==mp::ExactAxis::Reduction&&k>=begin);
        out[std::size_t(m)*N+n]+=(exact?double(av):rounded(av,mode))*(exact?double(bv):rounded(bv,mode));
    }
    return out;
}
void raw_gemm(mp::Policy mode,bool ta,bool tb,int M,int N,int K,mp::ExactAxis axis=mp::ExactAxis::None,int begin=0) {
    Tensor a(ta?std::vector<int>{K,M}:std::vector<int>{M,K});fill(a,.17f);
    Tensor b(tb?std::vector<int>{N,K}:std::vector<int>{K,N});fill(b,.23f);
    auto da=a.to(Device::GPU),db=b.to(Device::GPU);
    Tensor guard=Tensor::ones({M*N+2},Device::GPU).mul(17.25f);
    auto out=guard.storage_view(1,{M,N});
    require(mp::gemm(mode,ta,tb,M,N,K,da.raw_data(),db.raw_data(),out.raw_data(),axis,begin),"WMMA raw GEMM rejected");
    gpu_parity_test::cuda_sync_or_throw("WMMA tails");
    close(out,dense(mode,values(a),values(b),ta,tb,M,N,K,axis,begin),"raw lowp operand oracle",3e-5);
    auto sentinels=values(guard);require(sentinels.front()==17.25&&sentinels.back()==17.25,"WMMA wrote output guard");
    close(da,values(a),"WMMA modified input",0);close(db,values(b),"WMMA modified weight",0);
    require(!mp::gemm(mode,ta,tb,M,N,K,da.raw_data(),db.raw_data(),da.raw_data()),"WMMA accepted output alias");
    require(!mp::gemm(mode,ta,tb,0,N,K,da.raw_data(),db.raw_data(),out.raw_data()),"WMMA accepted empty geometry");
    require(!mp::gemm(mp::Policy::ExactFP32,ta,tb,M,N,K,da.raw_data(),db.raw_data(),out.raw_data()),"WMMA silently accepted exact mode");
}
// This checks the unchanged controltail_fp32_v1 arithmetic bit for bit. The
// mixed prefix is generated by the same lowp pass with both suffix operands
// zeroed, then combined with an independent host wave32-order FP32 oracle.
void controltail_order(mp::Policy mode,bool ta,bool tb,int M,int N,int K,mp::ExactAxis axis,int begin) {
    Tensor a(ta?std::vector<int>{K,M}:std::vector<int>{M,K});fill(a,.17f);
    Tensor b(tb?std::vector<int>{N,K}:std::vector<int>{K,N});fill(b,.23f);
    std::vector<float> av(a.data(),a.data()+a.size),bv(b.data(),b.data()+b.size);
    std::vector<double> expected(std::size_t(M)*N);
    if(axis==mp::ExactAxis::Reduction) {
        auto pa=a.clone(),pb=b.clone();
        for(int x=begin;x<K;++x) {
            for(int row=0;row<M;++row) pa.data()[ta?std::size_t(x)*M+row:std::size_t(row)*K+x]=0;
            for(int col=0;col<N;++col) pb.data()[tb?std::size_t(col)*K+x:std::size_t(x)*N+col]=0;
        }
        auto ga=pa.to(Device::GPU),gb=pb.to(Device::GPU);
        auto prefix=Tensor::uninitialized({M,N},Device::GPU);
        require(mp::gemm(mode,ta,tb,M,N,K,ga.raw_data(),gb.raw_data(),prefix.raw_data()),"WMMA prefix rejected");
        expected=values(prefix);
    }
    auto ga=a.to(Device::GPU),gb=b.to(Device::GPU);
    // A poisoned destination proves every valid cell is freshly overwritten;
    // the production path now allocates this destination without zero filling.
    auto poison=Tensor::ones({M*N+2}).mul(std::numeric_limits<float>::quiet_NaN());
    poison.data()[0]=poison.data()[M*N+1]=17.25f;
    auto guard=poison.to(Device::GPU),out=guard.storage_view(1,{M,N});
    require(mp::gemm(mode,ta,tb,M,N,K,ga.raw_data(),gb.raw_data(),out.raw_data(),axis,begin),"controltail ordering enqueue");
    auto got=values(out);
    for(int row=0;row<M;++row) for(int col=0;col<N;++col) {
        const auto i=std::size_t(row)*N+col;
        const bool exact=axis==mp::ExactAxis::Reduction||
            (axis==mp::ExactAxis::OutputRows&&row>=begin)||(axis==mp::ExactAxis::OutputCols&&col>=begin);
        require(std::isfinite(got[i]),"WMMA uninitialized output leaked poison");
        if(!exact) continue;
        float value=controltail_oracle::dot(av,bv,ta,tb,M,N,K,row,col,axis==mp::ExactAxis::Reduction?begin:0);
        if(axis==mp::ExactAxis::Reduction) value=float(expected[i])+value;
        if(controltail_oracle::bits(float(got[i]))!=controltail_oracle::bits(value))
            throw std::runtime_error("controltail_fp32_v1 ordering changed row="+std::to_string(row)+" col="+std::to_string(col));
    }
    auto sentinels=values(guard);require(sentinels.front()==17.25&&sentinels.back()==17.25,"controltail output guard");
}
Mamba3State state(const mb::Shape& s,float scale) {
    Mamba3State x{Tensor::zeros({s.batch,s.heads,s.rotary_pairs}),Tensor::zeros({s.batch,s.heads,s.head_dim,s.state_dim}),
        Tensor::zeros({s.batch,s.heads,s.rank,s.state_dim}),Tensor::zeros({s.batch,s.heads,s.head_dim})};
    for(auto* t:{&x.phase,&x.ssm,&x.k,&x.v}) fill(*t,scale);return x;
}
Mamba3State device(const Mamba3State& s) {return {s.phase.to(Device::GPU),s.ssm.to(Device::GPU),s.k.to(Device::GPU),s.v.to(Device::GPU)};}
ref::State reference(const Mamba3State& s) {return {values(s.phase),values(s.ssm),values(s.k),values(s.v)};}
void close_state(const Mamba3State& s,const ref::State& r) {
    close(s.phase,r.phase,"phase FP32");close(s.ssm,r.ssm,"SSM FP32");close(s.k,r.k,"K FP32");close(s.v,r.v,"raw V FP32");
}
void full_layer(mp::Policy mode,bool mimo,bool norm) {
    Mamba3Config c;c.expand=1;c.head_dim=4;c.state_dim=128;c.n_groups=1;c.mimo=mimo;c.mimo_rank=4;c.outproj_norm=norm;
    const mb::Shape s{2,3,8,2,1,4,128,mimo?4:1,32,mimo,norm,c.norm_eps,c.a_floor};
    Mamba3Layer layer(8,c);layer.to(Device::GPU);auto params=layer.parameters();
    Tensor x({2,3,8});fill(x,.11f);Tensor dy({2,3,8});fill(dy,.012f);
    for(int i=24;i<48;++i) {x.data()[i]=std::numeric_limits<float>::quiet_NaN();dy.data()[i]=std::numeric_limits<float>::quiet_NaN();}
    auto xv=values(x),yv=values(dy);for(int i=24;i<48;++i)xv[i]=yv[i]=0;
    const auto win=values(params[0]->data),wout=values(params[1]->data);
    auto initial=state(s,.01f),seed=state(s,.004f);
    const int control_begin=2*s.inner()+2*s.bc();
    ref::BlockInputs inputs{s,dense(mode,xv,win,false,true,6,s.width(),8,mp::ExactAxis::OutputCols,control_begin)};
    for(std::size_t i=2;i<params.size();++i) {auto v=values(params[i]->data);inputs.core.insert(inputs.core.end(),v.begin(),v.end());}
    inputs.valid_lengths={3,0};auto expected=ref::block_forward(inputs,reference(initial));
    env(name(mode));auto tape=layer.forward_owned(x.to(Device::GPU),device(initial),{3,0});
    require(tape->projection_runtime_identity()==mp::identity(mode),"tape did not capture WMMA identity");
    close(tape->output(),dense(mode,expected.output,wout,false,true,6,8,s.inner()),"lowp full layer forward",6e-4);
    close_state(tape->snapshot_final_state(),expected.final_state);
    // Changing the external flag cannot reinterpret a retained tape's algorithm.
    env("exact_fp32");
    auto dmid=dense(mode,yv,wout,false,false,6,s.inner(),8);
    auto gradients=ref::block_backward(inputs,reference(initial),dmid,reference(seed));
    auto got=layer.backward_owned(tape,dy.to(Device::GPU),device(seed));
    close_state(got.initial_state,gradients.initial_state);
    close(got.input,dense(mode,gradients.projection,win,false,false,6,8,s.width(),mp::ExactAxis::Reduction,control_begin),"lowp input VJP",8e-4);
    close(got.parameters[0],dense(mode,gradients.projection,xv,true,false,s.width(),8,6,mp::ExactAxis::OutputRows,control_begin),"lowp in-proj VJP",8e-4);
    close(got.parameters[1],dense(mode,yv,expected.output,true,false,8,s.inner(),6),"lowp out-proj VJP",8e-4);
    std::size_t off=0;for(std::size_t i=2;i<params.size();++i) {const auto n=std::size_t(params[i]->data.size);
        close(got.parameters[i],std::vector<double>(gradients.core.begin()+off,gradients.core.begin()+off+n),params[i]->name.c_str(),8e-4);off+=n;}
    require(tape->audit_status()==std::vector<int>({0,0}),"lowp full layer status failed");
    require(layer.telemetry().projection_wmma_gemms==6,"did not dispatch all six WMMA projections");
    layer.publish(got);for(auto* p:params)require(p->has_gradient(),"lowp projection missed parameter gradient");
    reject([&]{layer.publish(got);},"lowp gradient publication reused");
    const auto exclusions=layer.no_weight_decay_parameters();require(exclusions.size()==2&&exclusions[0]==params[4]&&exclusions[1]==params[7],"WMMA changed no-decay registry");
}
void continuation(mp::Policy mode) {
    env(name(mode));
    ModelConfig cfg;cfg.architecture_schema_version=3;cfg.mamba3_enabled=true;
    cfg.mamba3_mimo=true;cfg.mamba3_mimo_rank=2;cfg.mamba3_state_dim=128;
    cfg.mamba3_outproj_norm=true;cfg.num_layers=1;cfg.d_model=8;cfg.vocab_size=32;
    cfg.n_heads=2;cfg.n_kv_heads=1;cfg.mamba_expand=1;cfg.mamba_head_dim=4;
    cfg.use_moe=false;cfg.use_ttt=false;cfg.attention_period=8;cfg.max_context_tokens=16;
    JambaModel model(cfg,Device::GPU);Trainer trainer(&model,.002f);
    trainer.phase_scheduler.progressive_qat_enabled=false;trainer.weight_decay=.01f;
    require(std::isfinite(trainer.train_step({1,2,3},{2,3,4})),"WMMA Trainer first loss invalid");
    auto base=std::filesystem::temp_directory_path()/(std::string("nsos-wmma-mamba3-")+name(mode));
    const auto model_path=base.string()+".model",state_path=base.string()+".trainer";
    model.save(model_path);trainer.save_training_state(state_path,model_path);
    bool identity_found=false;for(const auto& entry:trainer.execution_identity_fields())
        if(entry.first=="mamba3.projection_arithmetic") identity_found=entry.second==mp::identity(mode);
    require(identity_found,"Trainer identity omitted WMMA arithmetic");
    env("exact_fp32");JambaModel bad_model(cfg,Device::GPU);bad_model.load(model_path);
    Trainer bad(&bad_model,.002f);const auto bad_before=values(bad_model.parameters()[0]->data);
    reject([&]{bad.load_training_state(state_path,model_path);},"WMMA sidecar resumed under exact arithmetic");
    require(bad.global_step_count==0&&bad.tokens_committed==0,"failed policy resume changed progress");
    close(bad_model.parameters()[0]->data,bad_before,"failed policy resume changed weights",0);
    env(name(mode));JambaModel resumed_model(cfg,Device::GPU);resumed_model.load(model_path);
    Trainer resumed(&resumed_model,.04f);resumed.load_training_state(state_path,model_path);
    const auto compare=[&](Trainer& continued,JambaModel& target) {
        const float expected=trainer.train_step({1,2,3},{2,3,4}),actual=continued.train_step({1,2,3},{2,3,4});
        require(std::isfinite(actual)&&std::abs(actual-expected)<1e-6f,"WMMA resumed loss diverged");
        require(continued.global_step_count==trainer.global_step_count&&continued.tokens_processed==trainer.tokens_processed&&
            continued.tokens_committed==trainer.tokens_committed,"WMMA resumed progress diverged");
        auto a=model.parameters(),b=target.parameters();require(a.size()==b.size(),"WMMA resumed registry");
        for(std::size_t i=0;i<a.size();++i)close(b[i]->data,values(a[i]->data),"WMMA resumed weights",2e-6);
    };
    compare(resumed,resumed_model);
    auto snapshot=trainer.capture_checkpoint_snapshot();snapshot->write(model_path,state_path);
    JambaModel snap_model(cfg,Device::GPU);snap_model.load(model_path);
    Trainer snap_resume(&snap_model,.04f);snap_resume.load_training_state(state_path,model_path);
    compare(snap_resume,snap_model);
    std::filesystem::remove(model_path);std::filesystem::remove(state_path);
}
void failure_and_policy() {
    env("garbage");reject([]{mp::policy();},"unknown lowp policy accepted");
    env("rdna_fp16_v1");Mamba3Config c;c.expand=1;c.head_dim=4;c.state_dim=8;
    Mamba3Layer cpu(8,c);reject([&]{cpu.forward_owned(Tensor::ones({1,2,8}));},"CPU lowp silently fell back");
    Mamba3Layer gpu(8,c);gpu.to(Device::GPU);auto p=gpu.parameters();
    auto weight=p[0]->data.cpu();weight.data()[0]=1e8f;p[0]->copy_data_from(weight.to(Device::GPU));
    auto tape=gpu.forward_owned(Tensor::ones({1,2,8},Device::GPU));
    require(tape->audit_status()[0]!=0,"finite FP32 to FP16 overflow escaped status gate");
    for(auto y:values(tape->output())) require(y==0,"FP16 overflow output was not gated");
    auto grads=gpu.backward_owned(tape,Tensor::ones({1,2,8},Device::GPU));
    reject([&]{gpu.publish(grads);},"FP16 overflow gradients published");
    for(auto* item:p) require(!item->has_gradient(),"failed WMMA VJP published partial gradient");
    // A finite large ANGLE projection is FP32 end-to-end, including VJP.
    // It must not overflow merely because unrelated B/C projections use FP16.
    Mamba3Layer control(8,c);control.to(Device::GPU);auto cp=control.parameters();
    auto cw=cp[0]->data.cpu();cw.data()[(cw.shape.dims[0]-1)*8]=1e8f;
    cp[0]->copy_data_from(cw.to(Device::GPU));
    auto controls=control.forward_owned(Tensor::ones({1,2,8},Device::GPU).mul(.01f));
    require(controls->audit_status()[0]==0,"FP32 angle suffix was cast to FP16");
    auto cg=control.backward_owned(controls,Tensor::ones({1,2,8},Device::GPU).mul(.01f));
    require(controls->audit_status()[0]==0,"FP32 angle VJP suffix was cast to FP16");
    control.publish(cg);
    env("exact_fp32");auto exact=gpu.forward_owned(Tensor::zeros({1,2,8},Device::GPU));
    require(exact->projection_runtime_identity()==mp::identity(mp::Policy::ExactFP32),"explicit exact fallback absent");exact->cancel();
    require(!mp::geometry(2147483647,1,1)&&!mp::geometry(50000,50000,1),"WMMA geometry overflow accepted");
}
}
int main() {
    return gpu_parity_test::run_parity("mamba3_projection_wmma",[] {
        set_matmul_precision_mode(0);
        for(auto mode:{mp::Policy::BF16,mp::Policy::FP16}) {
            require(mp::supported(mode),"RDNA3 WMMA build/device unavailable");
            for(auto flags:{std::pair{false,false},std::pair{false,true},std::pair{true,false},std::pair{true,true}})
                for(auto dims:{std::array<int,3>{1,1,1},std::array<int,3>{17,33,35},std::array<int,3>{65,47,63}})
                    raw_gemm(mode,flags.first,flags.second,dims[0],dims[1],dims[2]);
            for(auto flags:{std::pair{false,false},std::pair{false,true},std::pair{true,false},std::pair{true,true}}) {
                raw_gemm(mode,flags.first,flags.second,17,33,35,mp::ExactAxis::OutputRows,13);
                raw_gemm(mode,flags.first,flags.second,17,33,35,mp::ExactAxis::OutputCols,29);
                raw_gemm(mode,flags.first,flags.second,17,33,35,mp::ExactAxis::Reduction,31);
            }
            for(auto flags:{std::pair{false,false},std::pair{false,true},std::pair{true,false},std::pair{true,true}})
                for(auto dims:{std::array<int,3>{1,1,1},std::array<int,3>{33,9,65},std::array<int,3>{65,19,513}})
                    for(auto axis:{mp::ExactAxis::OutputRows,mp::ExactAxis::OutputCols,mp::ExactAxis::Reduction}) {
                        const int extent=axis==mp::ExactAxis::OutputRows?dims[0]:axis==mp::ExactAxis::OutputCols?dims[1]:dims[2];
                        for(int begin:{0,std::min(31,extent-1),extent-1}) controltail_order(mode,flags.first,flags.second,dims[0],dims[1],dims[2],axis,begin);
                    }
            full_layer(mode,false,false);full_layer(mode,true,true);continuation(mode);
        }
        failure_and_policy();env(nullptr);
        gpu_parity_test::cuda_sync_or_throw("Mamba3 WMMA completion");
    });
}
